### PR TITLE
feat: Support juju 3.2

### PR DESCRIPTION
**Pull request by jneo8**

### CODE REVIEW

**Comment by jneo8** [comment]
block by #69

**Review by Pjack — APPROVED** [review]

**Comment by jneo8** [comment]
block by https://github.com/juju/python-libjuju/issues/1039

**Review by sudeephb — APPROVED** [review]

**Review by agileshaw — COMMENTED** [review]
Do we really need to have one branch per minor version of Juju? Can't we simply use a `3` track to handle all 3.x juju compatibility (I think libjuju is suppose to have this wider compatibility range)? 

I'm worried about the future overheads: if we handle all minor versions separately, for each version we would need to create a new branch and maintain their dependency changes, requesting a new snap channel, updating compatibility matrix in documentation, and potentially other additional work.

**Comment by jneo8** [comment]
According to the comment from juju team, [link](https://github.com/juju/python-libjuju/issues/1039#issuecomment-2037528699). I think we need to change our strategy here.

**Pull request closed without merging**
